import React, { useState } from 'react';
import { Share } from '@capacitor/share';
import { motion } from 'motion/react';
import { Check, Trash2, Share2, Plus, CheckCircle2 } from 'lucide-react';
import toast from 'react-hot-toast';
import PageWrapper from '../components/layout/PageWrapper';
import Loader from '../components/common/Loader';
import EmptyState from '../components/common/EmptyState';
import { useShoppingList } from '../hooks/useShoppingList';
import { useAdmin } from '../hooks/useAdmin';

const ShoppingList = () => {
  const { shoppingList, loading, addItem, togglePurchased, clearPurchased, removeItem } = useShoppingList();
  const { isAdmin } = useAdmin();
  const [newItemName, setNewItemName] = useState('');

  const handleAddManualItem = async (e) => {
    e.preventDefault();
    if (!newItemName.trim()) return;
    
    try {
      await addItem({ name: newItemName.trim(), priority: 'normal' });
      setNewItemName('');
      toast.success('Added to list');
    } catch (error) {
      toast.error('Failed to add item');
    }
  };

  const handleExport = async () => {
    const unpurchased = shoppingList.filter(item => !item.isPurchased);
    
    const urgent = unpurchased.filter(i => i.priority === 'urgent');
    const soon = unpurchased.filter(i => i.priority === 'soon');
    const normal = unpurchased.filter(i => i.priority === 'normal');

    const now = new Date();
    const formattedDate = now.toLocaleString();

    let text = `🛒 SNACK TRACKER — SHOPPING LIST\n`;
    text += `Generated: ${formattedDate}\n`;
    text += `─────────────────────────────────\n`;

    if (urgent.length > 0) {
      text += `🔴 URGENT (Buy Soon)\n`;
      urgent.forEach(i => {
        text += `  • ${i.name} — ${i.quantity !== undefined ? `${i.quantity} left` : 'Out of stock'}\n`;
      });
      text += `\n`;
    }

    if (soon.length > 0) {
      text += `🟡 COMING UP LOW\n`;
      soon.forEach(i => {
        text += `  • ${i.name} — ${i.quantity !== undefined ? `${i.quantity} left` : 'Low stock'}\n`;
      });
      text += `\n`;
    }

    if (normal.length > 0) {
      text += `📋 OTHER ITEMS\n`;
      normal.forEach(i => {
        text += `  • ${i.name}\n`;
      });
      text += `\n`;
    }

    text += `─────────────────────────────────\n`;
    text += `Total items to buy: ${unpurchased.length}\n`;
    text += `Generated by Super Snack Snatcher`;

    try {
      await Share.share({
        title: 'Shopping List',
        text: text,
        dialogTitle: 'Share Shopping List',
      });
      toast.success('Shopping list exported!');
    } catch (error) {
      console.error('Error sharing:', error);
      // Fallback for web if Share API fails
      navigator.clipboard.writeText(text);
      toast.success('Copied to clipboard!');
    }
  };

  if (loading) return <PageWrapper><Loader /></PageWrapper>;

  const urgentItems = shoppingList.filter(i => i.priority === 'urgent' && !i.isPurchased);
  const soonItems = shoppingList.filter(i => i.priority === 'soon' && !i.isPurchased);
  const normalItems = shoppingList.filter(i => i.priority === 'normal' && !i.isPurchased);
  const purchasedItems = shoppingList.filter(i => i.isPurchased);

  const renderList = (items, title) => {
    if (items.length === 0) return null;
    return (
      <div className="mb-6">
        {title && <h3 className="text-sm font-bold text-[var(--color-text-secondary)] uppercase tracking-wider mb-3">{title}</h3>}
        <ul className="space-y-3">
          {items.map(item => (
            <motion.li 
              key={item.id}
              layout
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9 }}
              className={`flex items-center justify-between p-4 rounded-2xl border-2 transition-all ${
                item.isPurchased 
                  ? 'bg-[var(--color-background)] border-[var(--color-border)] opacity-60' 
                  : item.priority === 'urgent'
                    ? 'bg-red-50 border-red-200'
                    : 'bg-white border-[var(--color-border)] shadow-sm'
              }`}
            >
              <div className="flex items-center space-x-4">
                {isAdmin && (
                  <button 
                    onClick={() => togglePurchased(item.id, item.isPurchased)}
                    className={`w-8 h-8 rounded-full border-2 flex items-center justify-center transition-colors shrink-0 ${
                      item.isPurchased 
                        ? 'bg-[var(--color-primary)] border-[var(--color-primary)] text-white' 
                        : 'border-[var(--color-border)] hover:border-[var(--color-primary-light)] bg-white'
                    }`}
                  >
                    {item.isPurchased && <Check size={18} strokeWidth={3} />}
                  </button>
                )}
                <span className={`font-bold text-lg ${item.isPurchased ? 'line-through text-[var(--color-text-secondary)]' : 'text-[var(--color-text-primary)]'}`}>
                  {item.name}
                </span>
              </div>
              
              <div className="flex items-center space-x-3">
                {!item.isPurchased && item.priority === 'urgent' && (
                  <span className="flex items-center space-x-1 text-xs font-bold text-red-700 bg-red-100 px-2 py-1 rounded-lg uppercase tracking-wider">
                    <div className="w-1.5 h-1.5 rounded-full bg-red-500" />
                    <span>Urgent</span>
                  </span>
                )}
                {!item.isPurchased && item.priority === 'soon' && (
                  <span className="flex items-center space-x-1 text-xs font-bold text-yellow-700 bg-yellow-100 px-2 py-1 rounded-lg uppercase tracking-wider">
                    <div className="w-1.5 h-1.5 rounded-full bg-yellow-500" />
                    <span>Soon</span>
                  </span>
                )}
                {isAdmin && (
                  <button 
                    onClick={() => removeItem(item.id)}
                    className="p-2 text-[var(--color-text-secondary)] hover:text-red-500 hover:bg-red-50 rounded-xl transition-colors shrink-0"
                  >
                    <Trash2 size={20} />
                  </button>
                )}
              </div>
            </motion.li>
          ))}
        </ul>
      </div>
    );
  };

  return (
    <PageWrapper className="pb-24">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-3xl font-display text-[var(--color-text-primary)] tracking-tight">Shopping List</h1>
          <p className="text-[var(--color-text-secondary)] mt-1 font-medium">Items to restock</p>
        </div>
        <button 
          onClick={handleExport}
          className="p-3 bg-[var(--color-primary-soft)] text-[var(--color-primary)] rounded-full hover:bg-[var(--color-primary-glow)] transition-colors shadow-sm"
        >
          <Share2 size={24} />
        </button>
      </div>

      {isAdmin && (
        <form onSubmit={handleAddManualItem} className="mb-8 flex space-x-2">
          <input
            type="text"
            value={newItemName}
            onChange={(e) => setNewItemName(e.target.value)}
            placeholder="Add custom item..."
            className="flex-1 px-4 py-3 bg-[var(--color-background)] border-2 border-[var(--color-border)] rounded-xl focus:outline-none focus:border-[var(--color-primary)] font-bold text-[var(--color-text-primary)]"
          />
          <button 
            type="submit"
            disabled={!newItemName.trim()}
            className="px-4 py-3 bg-[var(--color-primary)] text-white rounded-xl font-bold disabled:opacity-50 transition-opacity flex items-center justify-center shadow-[0_4px_14px_rgba(124,58,237,0.3)] hover:bg-[var(--color-primary-light)]"
          >
            <Plus size={24} />
          </button>
        </form>
      )}

      {shoppingList.length === 0 ? (
        <EmptyState 
          icon={<CheckCircle2 size={48} className="text-[var(--color-primary-light)]" strokeWidth={1.5} />} 
          title="All stocked up!" 
          message="Your shopping list is empty." 
        />
      ) : (
        <>
          {renderList(urgentItems, "Urgent 🔴")}
          {renderList(soonItems, "Soon 🟡")}
          {renderList(normalItems, "Normal 📋")}
          
          {purchasedItems.length > 0 && (
            <div className="mt-8 pt-6 border-t-2 border-[var(--color-border)]">
              <div className="flex justify-between items-center mb-4">
                <h3 className="text-sm font-bold text-[var(--color-text-secondary)] uppercase tracking-wider">Already Purchased ✅</h3>
                {isAdmin && (
                  <button 
                    onClick={clearPurchased}
                    className="text-sm font-bold text-red-500 hover:text-red-600 bg-red-50 px-3 py-1 rounded-lg transition-colors"
                  >
                    Clear All
                  </button>
                )}
              </div>
              {renderList(purchasedItems, "")}
            </div>
          )}
        </>
      )}
    </PageWrapper>
  );
};

export default ShoppingList;
